### ISSUE TITLE
Wrong analysis of adjectives after a verb

### ISSUE THREAD

**Issue by EricP1** [sammous/spacy-lefff#17]
With Spacy version 2.1.3. on Windows 10, Python 3.7.2
With the fr_core_news_md model language
There is a bad analysis of a construction such like this one (a verb followed by an adjective)

"Une personne fait une déclaration qu'elle sait fausse ou trompeuse."

The verb "savoir" is analysed as an auxiliary which is wrong because this is a full verb. As well, the token "fausse" is wrongly analyzed as a verb whereas it's an adjective (at least trompeuse is correctly analysed as an adjective).

This analysis has not been tested with spacy-Leff (I am attempting to install it but installation problems/warnings have prevented me to do so until now - still trying to resolve the issue), but this improvement should definitely be implemented in a future version of spacy-Leff.

Thanks!

**Comment by sammous** [comment]
For the first part of your comment, it is not really related to this package, but from `spacy` directly.
Maybe you can open an issue directly on spaCy's repository, but I think it is just coming from the part of speech model that is not 100% accurate.
For your problem related with `spacy-lefff`, maybe can you tell me what coding environment you are using and some screenshots of the errors returned ?
Thanks!
