### ISSUE TITLE
Exception when the malt_parser property of a token is missing

### ISSUE THREAD

**Issue by asterbini** [sammous/spacy-lefff#19]
When the token property token._.malt parser is missing lefff throws an exception at line 64 of lefff.py

This can be fixed by changing the line to
`t = token._.melt_tagger.lower() if self.after_melt and hasattr(token._, 'melt_tagger') else token.pos_`

**Comment by CrazyBatkin** [comment]
I've had the same problem, except your fix didn't work for me. The `token` actually _has_ the attribute `melt_tagger`, but it is set to `None`. So to fix the problem, I changed the line to:
`try:`
`t = token._.melt_tagger.lower() if self.after_melt and hasattr(token._, 'melt_tagger') else token.pos_`
`except AttributeError:`
`t = token.pos_`

**Comment by sammous** [comment]
thank you for reporting the issue, i will fix this asap. Can you give me the example that raised the issue so i can update my test case accordingly ?

**Comment by CrazyBatkin** [comment]
[19.txt](https://github.com/sammous/spacy-lefff/files/3500166/19.txt)
Here is the file that's causing the issue for me.

**Comment by sammous** [comment]
Is the exception you have coming from the print statement I forgot to remove ? https://github.com/sammous/spacy-lefff/blob/master/spacy_lefff/lefff.py#L62
![image](https://user-images.githubusercontent.com/7331072/63001348-08067400-bea6-11e9-8137-994b4c7566f2.png)
I updated last week the code to keep default values if nothing is found and forgot this type.
Or do you actually get a Python error ?

**Comment by CrazyBatkin** [comment]
`File "D:\Documents\ML-PDF-Reader\test.py", line 109, in test`
  `processed_doc = nlp(text)`
`File "C:\Program Files\Python35\Lib\site-packages\spacy\language.py", line 402, in __call__`
  `doc = proc(doc, **component_cfg.get(name, {}))`
`File "C:\Program Files\Python35\Lib\site-packages\spacy_lefff\lefff.py", line 69, in __call__`
  `t = token._.melt_tagger.lower() if self.after_melt and hasattr(token._, 'melt_tagger') else token.pos_`

`builtins.AttributeError: 'NoneType' object has no attribute 'lower'`

Here is the exception I'm getting. The code i've used is the one from [here](https://spacy.io/universe/project/spacy-lefff), and the nlp model is `fr_core_news_sm`

**Comment by sammous** [comment]
great thank you, apparently the problem comes from the breakline.
this works
```
nlp("some text")
```
but this doesn't
```
nlp("some text\n")
```
