### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Nebraw** [sammous/spacy-lefff#34]
Hello Hello,

I wanted to use your library for a NLP project but when I try to use the POSTagger, I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: '*/.user_conda/envs/conda_env/lib/python3.7/site-packages/spacy_lefff/data/tagger/models/fr/lexicon.json'

The line that make the error is this one:

pos = POSTagger()

There is some more files to download or i messing something?

Thank you and have a great day.

**Comment by sammous** [comment]
hello, it should the first time download everything.
could you retry from a fresh environment?

**Comment by Nebraw** [comment]
i use the commande pip install spacy-lefff to get the project, i will retry in other environnement.

**Comment by Nebraw** [comment]
I trie in new environnement and i get the same error :

[Errno 2] No such file or directory: '/export/home/cse190013/.user_conda/envs/env_test/lib/python3.7/site-packages/spacy_lefff/data/tagger/models/fr/lexicon.json'

spacy==3.0.0
spacy-lefff==0.4.0
spacy-legacy==3.0.2

**Comment by sammous** [comment]
can you tell me which python environment you are using ? Conda, python 3.7 ?
Which OS are you using ?

**Comment by Nebraw** [comment]
Where are my manners, sorry.

OS: Linux
Conda 4.6.14
Python 3.6.7

**Comment by sammous** [comment]
Could you try running into a container image ? 
`docker run -it python:3.6-slim /bin/bash`
`pip install spacy-lefff`
then try to reproduce your error ?
I have the feeling it is somehow due to your environment. In the meantime I would use a docker image to not block your development.

**Comment by Nebraw** [comment]
I try on a other computer, i don't succeed to reproduce my error. 
So the errors  come from my environnement lets go more debug now youhou ....

Thank you for everything and sorry for the troubles. 
Have a great day and good luck for the futur.

**Comment by sammous** [comment]
sure no worries
