### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by spitis** [sammous/spacy-lefff#6]
Thanks for this. Managed to get to work on Python 3 with spacy > 2.0.9 (2.0.11) -- at least I think it works. 

1. 2to3 all files
2. in melt_tagger.py, change `win /= 2` to `win = win // 2`
3. in melt_tagger.py, add `, encoding='latin1'` as an argument to np.load

Not sure if still works on Python 2 with these modifications. 

Should mark it as Python 2 somewhere until Python 3 support added.

**Comment by sammous** [comment]
Hi,
Thank you for your comment, I should indeed specify it that it works only on `Python 2` .
Updating it to python 3 should not take too much time.
I'll work on it ASAP.
Cheers
